import type { MetricEvidence, NumericBand, PresentationBands } from "@/lib/face/scoring/evidence-types";
import {
  ANIC_2008,
  DISTORTION_2023,
  FANG_2011,
  FARKAS_1994,
  FORTES_2014,
  KHOSHAB_2021,
  LANGLOIS_2000,
  LIM_2022,
  MAV_2025,
  MEDIAPIPE_DOCS,
  NAINI_CONVEXITY_2012,
  NAINI_MENTOLABIAL_2017,
  OKUMURA_2025,
  PALLETT_2010,
  PASKHOVER_2018,
  RHODES_2001,
  RHODES_2006,
  SINNO_2012,
  VAN_DONGEN_2011,
} from "@/lib/face/scoring/literature";

function range(min: number, max: number, center?: number): NumericBand {
  return center === undefined ? { min, max } : { min, max, center };
}

function display(min: number, max: number, sigma: number): PresentationBands {
  return {
    harmoniousRange: range(min, max),
    sigmaLow: sigma,
    sigmaHigh: sigma,
  };
}

const CONTEXT = [KHOSHAB_2021, FANG_2011, FARKAS_1994, MEDIAPIPE_DOCS];
const SYMMETRY_REFS = [RHODES_2006, RHODES_2001, LANGLOIS_2000, VAN_DONGEN_2011];
const CLOSE_RANGE = [PASKHOVER_2018, DISTORTION_2023];

const SYMMETRY_LIMITS = [
  "The literature supports a modest preference for symmetry. It does not publish this percent cutoff.",
  "The low end is a measurement-noise deadband. Natural asymmetry inside the harmony range is expected.",
  "These are 2D photographic differences, not the fluctuating-asymmetry indices used in the cited experiments.",
];

function symmetry(
  metricId: string,
  group: MetricEvidence["group"],
  harmoniousMax: number,
  sigma: number,
  reliability: number,
  budget: string[],
): MetricEvidence {
  return {
    metricId,
    group,
    view: "front",
    scoringShape: "lower-is-better",
    bands: {
      neutral: {
        aestheticTarget: range(0, Math.min(1.2, harmoniousMax * 0.35)),
        harmoniousRange: range(0, harmoniousMax),
        sigmaLow: sigma,
        sigmaHigh: sigma,
      },
    },
    uncertainty: Math.min(0.8, harmoniousMax * 0.2),
    evidenceType: "direct-attractiveness",
    evidenceTier: 1,
    evidenceLevel: "moderate",
    measurementReliability: reliability,
    formulaCompatibility: 0.45,
    scoreEligible: true,
    perspectiveSensitive: false,
    sourcePopulation: "Attractiveness experiments on symmetry and averageness, not a single demographic cutoff",
    references: SYMMETRY_REFS,
    limitations: SYMMETRY_LIMITS,
    formulaCompatibilityNotes: [
      "Direction (lower asymmetry scores higher) follows the experiments. The percent scale is a HarmonyLabs photographic summary.",
    ],
    accuracyBudget: budget,
  };
}

function extremeness(
  metricId: string,
  group: MetricEvidence["group"],
  min: number,
  max: number,
  sigma: number,
  reliability: number,
  perspectiveSensitive: boolean,
  notes: string[],
  budget: string[],
): MetricEvidence {
  return {
    metricId,
    group,
    view: "front",
    scoringShape: "extremeness",
    bands: { neutral: { harmoniousRange: range(min, max), sigmaLow: sigma, sigmaHigh: sigma } },
    evidenceType: "anthropometric-proportion",
    evidenceTier: 3,
    evidenceLevel: "low",
    measurementReliability: reliability,
    formulaCompatibility: 0.7,
    scoreEligible: true,
    perspectiveSensitive,
    sourcePopulation: "Cross-population anthropometry. No ancestry is inferred, and the band is intentionally wide.",
    references: [FANG_2011, FARKAS_1994, KHOSHAB_2021, LANGLOIS_2000],
    limitations: [
      "There is no formula-compatible attractiveness optimum for this ratio.",
      "The interval is a disproportion screen. Values inside it are not ranked toward a population mean.",
      "Equal neoclassical canons and phi are not targets.",
      ...notes,
    ],
    formulaCompatibilityNotes: notes,
    accuracyBudget: budget,
  };
}

function informational(
  metricId: string,
  group: MetricEvidence["group"],
  view: MetricEvidence["view"],
  min: number,
  max: number,
  limitations: string[],
  notes: string[],
  budget: string[],
  references: MetricEvidence["references"] = CONTEXT,
): MetricEvidence {
  return {
    metricId,
    group,
    view,
    scoringShape: "extremeness",
    bands: { neutral: display(min, max, Math.max(0.05, (max - min) / 6)) },
    evidenceType: "unsupported",
    evidenceTier: 4,
    evidenceLevel: "insufficient",
    measurementReliability: 0.45,
    formulaCompatibility: 0.3,
    scoreEligible: false,
    perspectiveSensitive: view === "profile",
    sourcePopulation: "Not used as a Harmony reference",
    references,
    limitations,
    formulaCompatibilityNotes: notes,
    accuracyBudget: budget,
  };
}

export const evidenceRegistry: Record<string, MetricEvidence> = {
  "pallett-length-ratio": {
    metricId: "pallett-length-ratio",
    group: "eyeSpacing",
    view: "front",
    scoringShape: "peaked-target",
    bands: {
      neutral: {
        aestheticTarget: range(0.343, 0.377, 0.36),
        harmoniousRange: range(0.326, 0.394),
        populationRange: range(0.326, 0.394),
        sigmaLow: 0.02,
        sigmaHigh: 0.02,
      },
    },
    uncertainty: 0.008,
    evidenceType: "direct-attractiveness",
    evidenceTier: 1,
    evidenceLevel: "moderate",
    measurementReliability: 0.72,
    formulaCompatibility: 0.85,
    scoreEligible: true,
    perspectiveSensitive: true,
    sourcePopulation: "Caucasian female faces in Pallett, Link, and Lee (2010); raters in their paired-comparison experiments",
    references: [PALLETT_2010, LANGLOIS_2000, RHODES_2006],
    limitations: [
      "Scored only when trichion is placed. The mesh forehead apex is not the hairline.",
      "The source faces were female and Caucasian. This is a relational ratio, not a race score, and generalization confidence is moderate.",
      "Their 46% width ratio is not used. HarmonyLabs does not measure the inner ear margins.",
    ],
    formulaCompatibilityNotes: [
      "Eye–mouth distance is the vertical span from the pupil midpoint to stomion. Face length is trichion to menton. Pallett used the eyes, the mouth, the hairline, and the chin.",
    ],
    accuracyBudget: ["Hairline placement", "pitch", "pupil and stomion localization", "close-camera perspective"],
  },
  "facial-convexity": {
    metricId: "facial-convexity",
    group: "profileConvexity",
    view: "profile",
    scoringShape: "peaked-target",
    bands: {
      neutral: {
        aestheticTarget: range(165.3, 173.1, 169.2),
        harmoniousRange: range(160, 178),
        populationRange: range(155, 180),
        sigmaLow: 6,
        sigmaHigh: 6,
      },
      masculine: {
        aestheticTarget: range(167.6, 171.6, 169.6),
        harmoniousRange: range(160, 178),
        sigmaLow: 6,
        sigmaHigh: 6,
      },
      feminine: {
        aestheticTarget: range(165.3, 169.3, 167.3),
        harmoniousRange: range(160, 178),
        sigmaLow: 6,
        sigmaHigh: 6,
      },
    },
    uncertainty: 1.5,
    evidenceType: "aesthetic-harmony",
    evidenceTier: 2,
    evidenceLevel: "moderate",
    measurementReliability: 0.7,
    formulaCompatibility: 0.78,
    masculineCompatibility: 0.7,
    feminineCompatibility: 0.7,
    scoreEligible: true,
    perspectiveSensitive: true,
    sourcePopulation:
      "Neutral target: Fortes et al. pleasant profiles (n = 30). Masculine and feminine centers: cephalometric profile-angle maxima in Chinese adults (PMID 40742908), used only when that presentation is selected.",
    references: [FORTES_2014, MAV_2025, NAINI_CONVEXITY_2012, ANIC_2008],
    limitations: [
      "The pleasant-cohort mean is not a proof that 169.2° is the unique optimum.",
      "Presentation-specific centers come from cephalograms correlated with photo ratings, not from the same 2D construction.",
      "Naini 2012 supports straighter profiles but uses a different convexity angle, so its ±10° to −12° limits are not copied.",
    ],
    formulaCompatibilityNotes: [
      "HarmonyLabs uses the interior angle at subnasale between glabella and pogonion, matching Fortes G′–Sn–Pg′ more closely than total convexity G′–Pn–Pg′.",
    ],
    accuracyBudget: ["Profile yaw short of a true lateral", "glabella and pogonion on the contour", "perspective", "expression"],
  },
  "nasolabial-angle": {
    metricId: "nasolabial-angle",
    group: "nasalProfile",
    view: "profile",
    scoringShape: "flat-target",
    bands: {
      neutral: {
        aestheticTarget: range(95, 105),
        harmoniousRange: range(90, 115),
        sigmaLow: 8,
        sigmaHigh: 8,
      },
      masculine: {
        aestheticTarget: range(93, 99, 95),
        harmoniousRange: range(90, 115),
        sigmaLow: 8,
        sigmaHigh: 8,
      },
      feminine: {
        aestheticTarget: range(100, 110, 105),
        harmoniousRange: range(90, 115),
        sigmaLow: 8,
        sigmaHigh: 8,
      },
    },
    uncertainty: 2,
    evidenceType: "direct-attractiveness",
    evidenceTier: 1,
    evidenceLevel: "moderate",
    measurementReliability: 0.62,
    formulaCompatibility: 0.72,
    scoreEligible: true,
    perspectiveSensitive: true,
    sourcePopulation: "783 Japanese adults rating one male and one female Japanese profile (Okumura et al. 2025)",
    references: [OKUMURA_2025, SINNO_2012, FORTES_2014],
    limitations: [
      "Only three angles were tested: 95°, 105°, and 115°. The peak is the best of those steps, not a continuous fit.",
      "Raters were predominantly women. Two model faces cannot represent every population.",
      "Sinno et al. used a Frankfort-perpendicular definition. Those degrees are not applied.",
      "Fortes et al. did not find nasolabial angle separated pleasant from unpleasant profiles.",
    ],
    formulaCompatibilityNotes: [
      "The cited angle is the columella tangent against the upper-lip tangent at subnasale. HarmonyLabs approximates those tangents with columella, subnasale, and labiale superius on a smoothed profile contour.",
    ],
    accuracyBudget: ["Columella localization", "upper-lip contour", "expression", "profile yaw", "perspective", "contour smoothing"],
  },
  "mentolabial-angle": {
    metricId: "mentolabial-angle",
    group: "chinProfile",
    view: "profile",
    scoringShape: "flat-target",
    bands: {
      neutral: {
        aestheticTarget: range(107, 118),
        harmoniousRange: range(98, 140),
        populationRange: range(90, 150),
        sigmaLow: 12,
        sigmaHigh: 14,
      },
      masculine: {
        aestheticTarget: range(107, 118, 112.5),
        harmoniousRange: range(98, 140),
        populationRange: range(90, 150),
        sigmaLow: 12,
        sigmaHigh: 14,
      },
      feminine: {
        aestheticTarget: range(107, 140),
        harmoniousRange: range(98, 150),
        sigmaLow: 12,
        sigmaHigh: 14,
      },
    },
    uncertainty: 2,
    evidenceType: "direct-attractiveness",
    evidenceTier: 1,
    evidenceLevel: "moderate",
    measurementReliability: 0.6,
    formulaCompatibility: 0.8,
    feminineCompatibility: 0.75,
    scoreEligible: true,
    perspectiveSensitive: true,
    sourcePopulation: "Observers of one idealized male Caucasian silhouette (Naini et al. 2017)",
    references: [NAINI_MENTOLABIAL_2017, FARKAS_1994],
    limitations: [
      "The manipulation used a male silhouette. The feminine profile therefore keeps the acceptable span and does not invent a female optimum.",
      "Farkas population means differ by sex and ancestry and are shown as population context, not as the target.",
      "A silhouette has no photographic texture, expression, or lens distortion.",
    ],
    formulaCompatibilityNotes: [
      "The angle at sublabiale between labiale inferius and pogonion matches the mentolabial angle that was manipulated.",
    ],
    accuracyBudget: ["Finding the mentolabial sulcus on the contour", "lip posture", "profile yaw", "pogonion"],
  },
  "eye-spacing-ratio": extremeness(
    "eye-spacing-ratio",
    "eyeSpacing",
    0.75,
    1.4,
    0.12,
    0.88,
    false,
    ["Intercanthal distance over mean eye width. Equality with one eye width is a neoclassical canon and is not the peak."],
    ["Canthus localization", "small yaw"],
  ),
  "nasal-width-intercanthal": extremeness(
    "nasal-width-intercanthal",
    "nasalWidthBalance",
    0.7,
    1.45,
    0.1,
    0.86,
    true,
    ["Alar width over intercanthal distance. Matching the eye spacing is a canon, not an attractiveness optimum."],
    ["Alar points", "canthi", "close-camera nasal enlargement"],
  ),
  "lip-height-ratio": extremeness(
    "lip-height-ratio",
    "oralProportions",
    0.35,
    1.05,
    0.12,
    0.75,
    false,
    ["Upper vermilion over lower vermilion. A 1:1.618 lip ratio is not used."],
    ["Vermilion borders", "lip color and shadow", "expression"],
  ),
  "mouth-width-ipd": extremeness(
    "mouth-width-ipd",
    "oralProportions",
    0.65,
    1.15,
    0.08,
    0.84,
    false,
    ["Mouth-corner width over interpupillary distance. No copied optimum."],
    ["Cheilion", "pupils", "smile"],
  ),
  "philtrum-proportion": extremeness(
    "philtrum-proportion",
    "oralProportions",
    0.18,
    0.45,
    0.05,
    0.8,
    false,
    ["Subnasale-to-labiale superius over subnasale-to-menton."],
    ["Subnasale", "lip border", "chin"],
  ),
  "chin-height-ratio": extremeness(
    "chin-height-ratio",
    "facialVerticals",
    0.45,
    0.8,
    0.06,
    0.82,
    false,
    ["Stomion-to-menton over subnasale-to-menton."],
    ["Mouth opening", "menton", "expression"],
  ),
  "lower-middle-ratio": extremeness(
    "lower-middle-ratio",
    "facialVerticals",
    0.75,
    1.45,
    0.12,
    0.84,
    true,
    ["Subnasale–menton over glabella–subnasale. Equal thirds are not the target. The hairline is not in this ratio."],
    ["Glabella", "subnasale", "menton", "pitch", "perspective"],
  ),
  "jaw-cheek-ratio": extremeness(
    "jaw-cheek-ratio",
    "jawBalance",
    0.62,
    0.95,
    0.08,
    0.4,
    true,
    ["Both widths use approximate gonion and zygion. Reliability is low on purpose."],
    ["Approximate zygion", "approximate gonion", "yaw", "2D breadth error"],
  ),
  "chin-jaw-width": extremeness(
    "chin-jaw-width",
    "jawBalance",
    0.55,
    1,
    0.08,
    0.42,
    false,
    ["Lateral chin over approximate gonion width."],
    ["Chin points", "approximate gonion"],
  ),
  "eye-level-asymmetry": symmetry("eye-level-asymmetry", "midlineSymmetry", 4, 2, 0.8, [
    "Pupil vertical localization",
    "camera roll",
    "expression",
  ]),
  "eye-width-symmetry": symmetry("eye-width-symmetry", "eyeMorphology", 8, 3, 0.78, [
    "Canthus localization",
    "partial blink",
  ]),
  "eye-height-symmetry": symmetry("eye-height-symmetry", "eyeMorphology", 10, 4, 0.7, [
    "Lid borders",
    "blink",
    "expression",
  ]),
  "mouth-level-asymmetry": symmetry("mouth-level-asymmetry", "midlineSymmetry", 5, 2.5, 0.72, [
    "Cheilion",
    "smile or speech",
  ]),
  "nasal-midline-deviation": symmetry("nasal-midline-deviation", "midlineSymmetry", 3.5, 1.8, 0.7, [
    "Pronasale",
    "pupil midline",
    "approximate face width in the denominator",
  ]),
  "chin-midline-deviation": symmetry("chin-midline-deviation", "midlineSymmetry", 3.5, 1.8, 0.68, [
    "Menton",
    "pupil midline",
    "approximate face width",
  ]),
  "nasal-alar-level": symmetry("nasal-alar-level", "nasalWidthBalance", 6, 2.5, 0.75, ["Alar points", "yaw"]),
  "jaw-level-symmetry": symmetry("jaw-level-symmetry", "jawBalance", 5, 2.2, 0.4, [
    "Approximate gonion",
    "mesh facial height",
  ]),
  "facial-width-height": informational(
    "facial-width-height",
    "facialVerticals",
    "front",
    0.6,
    0.9,
    [
      "Not a classical facial index. Width is approximate zygion and height starts at the mesh forehead, not trichion or nasion.",
      "Face width varies across populations. A narrower mesh is not scored as more attractive.",
    ],
    ["Pallett's 46% width ratio needs the inner ear margins and is not substituted here."],
    ["Approximate zygion", "mesh apex", "yaw", "perspective"],
    [LIM_2022, FANG_2011, PALLETT_2010, KHOSHAB_2021],
  ),
  "upper-third": informational(
    "upper-third",
    "facialVerticals",
    "front",
    0.2,
    0.4,
    [
      "This is the mesh-brow span, from the face-mesh apex to glabella, as a share of mesh apex to menton.",
      "It is not the trichion–glabella facial third and is not scored against equal-thirds canons.",
    ],
    ["Trichion-based literature is not applied."],
    ["Mesh boundary instead of hairline"],
    [KHOSHAB_2021, MEDIAPIPE_DOCS],
  ),
  "middle-third": informational(
    "middle-third",
    "facialVerticals",
    "front",
    0.25,
    0.45,
    [
      "Share of the mesh apex–menton span from glabella to subnasale. The denominator includes the mesh brow, so this is not a classical facial third.",
    ],
    ["Equal thirds are not a Harmony target. The lower-to-middle ratio uses the landmarks that do not need the hairline."],
    ["Mesh apex in the denominator", "pitch"],
    [KHOSHAB_2021],
  ),
  "lower-third": informational(
    "lower-third",
    "facialVerticals",
    "front",
    0.25,
    0.45,
    ["Share of the mesh apex–menton span from subnasale to menton. Same denominator limitation as the middle mesh share."],
    ["Not scored as a classical lower third."],
    ["Mesh apex in the denominator"],
    [KHOSHAB_2021],
  ),
  "intercanthal-face-ratio": informational(
    "intercanthal-face-ratio",
    "eyeSpacing",
    "front",
    0.15,
    0.28,
    ["Divides a reliable canthus span by approximate zygion width. The face-width denominator is too uncertain to score."],
    ["The intercanthal-to-eye-width ratio is the scored relational alternative."],
    ["Approximate zygion", "canthi"],
    [LIM_2022, FANG_2011],
  ),
  "interpupillary-face-ratio": informational(
    "interpupillary-face-ratio",
    "eyeSpacing",
    "front",
    0.35,
    0.55,
    [
      "Pupil span over approximate zygion width. Pallett's 0.46 optimum used inner ear margins, so that number is not attached.",
    ],
    ["Do not read the display scale as the Pallett width ratio."],
    ["Approximate zygion", "pupils"],
    [PALLETT_2010, LIM_2022],
  ),
  "eye-face-width": informational(
    "eye-face-width",
    "eyeMorphology",
    "front",
    0.14,
    0.24,
    ["Mean eye width over approximate facial width. Not scored."],
    ["Eye width relative to intercanthal distance is the scored spacing metric."],
    ["Approximate zygion"],
    [LIM_2022],
  ),
  "canthal-tilt": informational(
    "canthal-tilt",
    "eyeMorphology",
    "front",
    -2,
    10,
    ["No formula-compatible attractiveness target in degrees was adopted. Head roll moves this angle."],
    ["Shown for inspection. Not a Harmony component."],
    ["Canthi", "camera roll"],
  ),
  "nasal-width-face": informational(
    "nasal-width-face",
    "nasalWidthBalance",
    "front",
    0.18,
    0.34,
    ["Alar width over approximate zygion width. Scoring it would treat population differences in nasal and facial width as a harmony error."],
    ["Nasal width relative to intercanthal distance is the scored alternative, and only as a wide disproportion screen."],
    ["Alare", "approximate zygion", "selfie perspective"],
    [...CLOSE_RANGE, FANG_2011, LIM_2022],
  ),
  "nasal-length-ratio": informational(
    "nasal-length-ratio",
    "nasalWidthBalance",
    "front",
    0.22,
    0.4,
    ["Nasion–subnasale over mesh forehead–menton. The denominator is not a standard morphological face height."],
    ["Not scored against nasal-length canons."],
    ["Nasion", "mesh apex", "perspective"],
  ),
  "nasofrontal-angle": informational(
    "nasofrontal-angle",
    "nasalProfile",
    "profile",
    110,
    145,
    [
      "The point angle glabella–nasion–rhinion only approximates a forehead tangent against the dorsum.",
      "Textbook nasofrontal ranges were not attached, because the tangent construction and the study population would not match.",
    ],
    ["Contour smoothing stabilizes the points. The angle stays informational."],
    ["Nasion", "dorsum tangent", "profile yaw"],
    [ANIC_2008, MEDIAPIPE_DOCS],
  ),
  "nasofacial-angle": informational(
    "nasofacial-angle",
    "nasalProfile",
    "profile",
    25,
    45,
    [
      "HarmonyLabs measures the smaller angle between nasion–rhinion and glabella–pogonion.",
      "Okumura et al. measured nasion–pronasale against a Frankfort vertical. Those 30° and 33° preferences are not copied.",
    ],
    ["Different reference line. Informational only."],
    ["Dorsum points", "pogonion", "missing Frankfort horizontal"],
    [OKUMURA_2025],
  ),
  "nasal-projection": informational(
    "nasal-projection",
    "nasalProfile",
    "profile",
    0.2,
    0.6,
    [
      "Custom HarmonyLabs tip offset: distance from pronasale to the nasion–subnasale line, divided by nasion–pronasale.",
      "This is not Goode's ratio. The alar-facial groove is not on the anterior silhouette, so a Goode target is not applied.",
    ],
    ["Labelled as a HarmonyLabs construction. Clinical 0.55–0.60 norms are not used."],
    ["Pronasale", "nasion–subnasale line", "perspective", "profile yaw"],
    [PASKHOVER_2018, MEDIAPIPE_DOCS],
  ),
  "chin-projection": informational(
    "chin-projection",
    "chinProfile",
    "profile",
    -0.06,
    0.16,
    [
      "Custom signed offset of pogonion from the glabella–menton line, divided by subnasale–menton.",
      "Facial convexity already carries the scored profile relationship. This construction is not given a separate clinical norm.",
    ],
    ["Informational, so it cannot double-count convexity."],
    ["Pogonion", "glabella–menton line", "profile yaw"],
  ),
};

export function evidenceFor(metricId: string): MetricEvidence {
  const evidence = evidenceRegistry[metricId];
  if (!evidence) throw new Error(`Missing evidence for ${metricId}`);
  return evidence;
}
